title: Obsidian-Douban
description: This is a plugin that can import movies/books/musics/notes/games info data from Douban for Obsidian .
theme: just-the-docs

url: https://threeyang3.github.io/douban-sync

aux_links: # remove if you don't want this link to appear on your pages
  Douban Sync on Github: https://github.com/threeyang3/douban-sync
search:
  focus_shortcut_key: 'k'
